/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	net "net"
)

// NodeApplyConfiguration represents an declarative configuration of the Node type for use
// with apply.
type NodeApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	VtepMac *string `json:"vtepMac,omitempty"`
	VtepIp  *net.IP `json:"vtepIp,omitempty"`
	NodeIP  *net.IP `json:"nodeIP,omitempty"`
}

// NodeApplyConfiguration constructs an declarative configuration of the Node type for use with
// apply.
func Node() *NodeApplyConfiguration {
	return &NodeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NodeApplyConfiguration) WithName(value string) *NodeApplyConfiguration {
	b.Name = &value
	return b
}

// WithVtepMac sets the VtepMac field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VtepMac field is set to the value of the last call.
func (b *NodeApplyConfiguration) WithVtepMac(value string) *NodeApplyConfiguration {
	b.VtepMac = &value
	return b
}

// WithVtepIp sets the VtepIp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VtepIp field is set to the value of the last call.
func (b *NodeApplyConfiguration) WithVtepIp(value net.IP) *NodeApplyConfiguration {
	b.VtepIp = &value
	return b
}

// WithNodeIP sets the NodeIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeIP field is set to the value of the last call.
func (b *NodeApplyConfiguration) WithNodeIP(value net.IP) *NodeApplyConfiguration {
	b.NodeIP = &value
	return b
}
