apiVersion: v1
kind: Pod
metadata:
  name: busybox-blue2
  namespace: default
  annotations: 
    jovik31.dev.tenants: tblue
spec:
  nodeName: kind-cluster-worker2
  containers:
  - name: busybox-blue2
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector: 
    jovik31.dev.tenantcni.tblue: Enabled

  restartPolicy: Always