apiVersion: v1
kind: Pod
metadata:
  name: busybox-green1
  namespace: default
  annotations: 
    jovik31.dev.tenants: tgreen
spec:
  nodeName: cluster-worker
  containers:
  - name: busybox-green1
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector: 
    jovik31.dev.tenantcni.tgreen: Enabled

  restartPolicy: Always