apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations: 
    jovik31.dev.tenants: tenant2
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector: 
    jovik31.dev.tenantcni.tenant2: Enabled

  restartPolicy: Always