apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: tenant-cluster-role
rules:
- apiGroups:
  - jovik31.dev
  resources:
  - tenants
  verbs:
  - list
  - watch
  - create
  - get
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - create
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  verbs:
  - list
  - watch
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: tenant-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-cluster-role
subjects:
- kind: ServiceAccount
  name: tenant-service-account
  namespace: default
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-tenantcni-config
  namespace: default
  labels:
    tier: node
    app: tenant
data:
  cni-conf.json: |
    {
      "name": "tenantcni",
      "cniVersion": "0.4.0",
      "type": "tenantcni",
      "dataDir": "/var/lib/cni/tenantcni",
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    tier: node
    app: tenant
  name: tenant
spec:
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      initContainers:
      - name: install-cni
        image: jovik31/tenant:1.1.0
        command: 
        - cp
        args:
        - f
        - /tenant
        - /opt/cni/bin/tenant
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      - name: install-cni
        image: jovik31/tenant:1.1.0
        command: 
        - cp
        args:
        - f
        - /etc/tenant/cni-conf.json
        - /etc/cni/net.d/10-tenant.conf
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: tenant
          mountPath: /etc/tenantcni/
      containers:
      - image: jovik31/tenant:1.1.0
        name: tenant
        command:
        - /tenantcni
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace 
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - name: var-lib-cni-tenantcni
          mountPath: /var/lib/cni/tenantcni
      volumes:
        - name: var-lib-cni-tenantcni
          hostPath:
            path: /var/lib/cni/tenantcni
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: tenant-service-account