apiVersion: jovik31.dev/v1alpha1
kind: Tenant
metadata:
  name: tenant2
spec:
  name: tenant2
  vni: 4
  prefix: 24
  nodes:
    - name: kind-cluster-worker
    - name: kind-cluster-worker2

           