// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jovik31/controller/pkg/client/clientset/versioned/typed/jovik31.dev/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeJovik31V1alpha1 struct {
	*testing.Fake
}

func (c *FakeJovik31V1alpha1) Tenants(namespace string) v1alpha1.TenantInterface {
	return &FakeTenants{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeJovik31V1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
